### PR TITLE
Rewritten to support the Ademco Panel

### PR DESCRIPTION
**Pull request by cthierman**
Completely rewrote code so as to support the Honeywell Ademco panel. However, noticed after the original author also released a new version 4 months ago... Somehow I didn't see that...
Well, I'll keep my version around for now.

### CODE REVIEW

**Comment by pakerfeldt** [comment]
I don’t understand. If you decided to rewrite everything, why are you submitting a pull request for this repository?

**Comment by cthierman** [comment]
Sorry Patrick.  Complete noob when it comes to git...  by the time I realized what I had done I didn’t know how to undo it. 

I was going to reach out to you but was even having trouble with that.  I have since deleted the fork and created a separate project.  

I see you actually wrote a Honeywell version.  But it’s not showing up in node red.  

I can set my version to private if you want. I based a lot on what you did, so you are completely in your right to ask me to withdraw it.  

Please let me know. And nice job. Love what you’ve done. Using your example as a base, I was quite amazed that I managed to get an almost complete rewrite to work well, in only a day. Given that this was my first venture into writing a pallet for node-red. 

I I contribute that to your clean coding style. This has been an awesome learning opportunity.  

I’ve made minor modes to fix others pallets before, but yours was nice cause it was better written.. easier to follow.  

Thanks again.

**Comment by pakerfeldt** [comment]
Hi,

We were all beginners at some point. I’m happy you found good use of my project. By all means, keep your fork! I just didn’t understand how your changes would be merged back to my project. I take no pride in what I’ve written and if people want to fork and adapt to their own needs I’m just happy!

Keep on hacking!

**Comment by cthierman** [comment]
Thanks man.  

So I created a new project and called it node-red-contrib-envisalink-ademco. 

Gave you credit.  

Thanks again.

**Pull request closed without merging**
